### ISSUE TITLE
Dependency Conflict with `algolia_helper` and `http` in `algolia_helper_flutter`

### ISSUE THREAD

**Issue by AkshayND** [algolia/algoliasearch-helper-flutter#91]
**Description:**

I am currently using the `algolia_helper_flutter` package in my `bizbhaarat` project. During the installation of `algolia_helper_flutter`, I encountered a dependency version solving failure. The issue arises when I try to run `flutter pub add algolia_helper_flutter`.

As per my understanding, the `algolia_helper_flutter` package has different versions depending on various versions of `algolia_helper`. 

For `algolia_helper_flutter`:

- Versions <0.1.2 depend on `algolia_helper ^0.1.0`
- Versions >=0.1.2 and <0.1.3 depend on `algolia_helper ^0.1.2`
- Versions >=0.1.3 and <0.1.4 depend on `algolia_helper ^0.1.3`
- Versions >=0.1.4 and <0.1.5 depend on `algolia_helper ^0.1.4`
- Versions ^0.1.5 depend on `algolia_helper ^0.1.5`
- Versions >=0.2.0 and <0.2.1 depend on `algolia_helper ^0.2.0`
- Versions >=0.2.1 and <0.2.3 depend on `algolia_helper ^0.2.1`
- Versions >=0.2.3 and <0.3.2 depend on `algolia_helper ^0.2.3`
- Versions >=0.3.2 depend on `algolia_helper ^0.3.2`

This results in a requirement of `algolia_helper ^0.1.0 or >=0.2.0 <0.3.0 or ^0.3.2` for every version of `algolia_helper_flutter`.

Additionally, every version of `algolia_helper` depends on `algolia ^1.1.1` which in turn depends on `http ^0.13.0`.

The problem arises as my project `bizbhaarat` depends on `http ^1.0.0` and `algolia_helper_flutter`. The dependency version of `http` in `bizbhaarat` and `algolia_helper_flutter` are conflicting.

This leads to a version solving failure.

**Expected Outcome:**

Ideally, `algolia_helper_flutter` should be compatible with `http ^1.0.0` or higher versions.

**Actual Outcome:**

`algolia_helper_flutter` is not compatible with `http ^1.0.0` causing version solving failure.

**Steps to reproduce:**

1. Create a new flutter project.
2. Add `http: ^1.0.0` and `algolia_helper_flutter: any` in the `pubspec.yaml` file.
3. Run the `flutter pub get` command.
4. Observe the version solving failure.

Please let me know if there is a workaround for this or if an update to address this issue is planned. Thank you for your assistance!

**Comment by devprotec** [comment]
I'm facing exactly the same issue here. My flutter pub get output looks like this:

[smart_tutor_gh_mobile] flutter pub get
Resolving dependencies...
Because algolia_helper_flutter >=0.2.1 <0.2.3 depends on algolia_helper ^0.2.1 and algolia_helper_flutter >=0.2.0 <0.2.1 depends on algolia_helper ^0.2.0, algolia_helper_flutter >=0.2.0 <0.2.3 requires algolia_helper ^0.2.0.
And because algolia_helper_flutter >=0.2.3 <0.3.2 depends on algolia_helper ^0.2.3, algolia_helper_flutter >=0.2.0 <0.3.2 requires algolia_helper ^0.2.0.
And because every version of algolia_helper depends on algolia ^1.1.1 which depends on http ^0.13.0, algolia_helper_flutter >=0.2.0 <0.3.2 requires http ^0.13.0.
So, because smart_tutor_gh_mobile depends on both http ^1.1.0 and algolia_helper_flutter ^0.2.0, version solving failed.
exit code 1

I've tried with different versions and I get almost the same thing.

**Comment by ogimgio** [comment]
found a solution?

**Comment by AkshayND** [comment]
No. I haven't

**Comment by bettkipronoh** [comment]
In the mean time you can override `http` librabry like this
```
dependency_overrides:
  http: ^1.0.0
```

**Comment by VladislavFitz** [comment]
Thank you for reporting this. A new version of Algolia Helper for Flutter will be released in the coming days. It replaces the community Dart client with the official one made by Algolia. This new client doesn't depend on the `http` library, so this issue will be solved. Stay tuned!

**Comment by VladislavFitz** [comment]
A new release is now available. The issue might be fixed.

**Comment by VladislavFitz** [comment]
Closing, since there is no more `http` dependency.
